# Generated by Django 5.2.7 on 2025-10-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id_recomendacion', models.AutoField(primary_key=True, serialize=False)),
                ('criterio', models.CharField(choices=[('perfil_usuario', 'Basado en Perfil'), ('resultado_test', 'Basado en Test'), ('historial_financiero', 'Basado en Historial'), ('temas_debiles', 'Basado en Áreas Débiles')], max_length=30)),
                ('fecha_recomendacion', models.DateTimeField(auto_now_add=True)),
                ('visto', models.BooleanField(default=False)),
                ('util', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
                'db_table': 'recomendacion',
            },
        ),
        migrations.CreateModel(
            name='RecursoAprendizaje',
            fields=[
                ('id_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('articulo', 'Artículo'), ('curso', 'Curso'), ('podcast', 'Podcast'), ('infografia', 'Infografía')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('enlace', models.URLField()),
                ('tematica', models.CharField(choices=[('presupuesto', 'Presupuesto Personal'), ('ahorro', 'Ahorro'), ('inversion', 'Inversión'), ('deudas', 'Manejo de Deudas'), ('credito', 'Crédito'), ('impuestos', 'Impuestos'), ('emprendimiento', 'Emprendimiento'), ('planificacion', 'Planificación Financiera')], max_length=30)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recurso de Aprendizaje',
                'verbose_name_plural': 'Recursos de Aprendizaje',
                'db_table': 'recurso_aprendizaje',
            },
        ),
    ]
