# Generated by Django 5.2.7 on 2025-10-01 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aprendizaje', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='id_recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='aprendizaje.recursoaprendizaje'),
        ),
    ]
