# Generated by Django 5.2.7 on 2025-10-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniTest',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.JSONField()),
                ('puntuacion_total', models.IntegerField()),
                ('nivel_determinado', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mini Test',
                'verbose_name_plural': 'Mini Tests',
                'db_table': 'minitest',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaTest',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('presupuesto', 'Presupuesto Personal'), ('ahorro', 'Ahorro'), ('inversion', 'Inversión'), ('deudas', 'Manejo de Deudas'), ('credito', 'Crédito')], max_length=30)),
                ('pregunta', models.TextField()),
                ('opciones', models.JSONField()),
                ('respuesta_correcta', models.IntegerField()),
                ('explicacion', models.TextField(blank=True)),
                ('nivel_dificultad', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='medio', max_length=20)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pregunta de Test',
                'verbose_name_plural': 'Preguntas de Test',
                'db_table': 'pregunta_test',
            },
        ),
    ]
