# Generated by Django 5.2.7 on 2025-10-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
