# Generated by Django 5.2.7 on 2025-10-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFinanciera',
            fields=[
                ('id_meta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('monto_objetivo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_objetivo', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='activa', max_length=15)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Meta Financiera',
                'verbose_name_plural': 'Metas Financieras',
                'db_table': 'meta_financiera',
            },
        ),
        migrations.CreateModel(
            name='RegistroFinanciero',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(choices=[('salario', 'Salario'), ('freelance', 'Freelance'), ('negocio', 'Negocio Propio'), ('inversion', 'Inversión'), ('otro_ingreso', 'Otro Ingreso'), ('alimentacion', 'Alimentación'), ('transporte', 'Transporte'), ('vivienda', 'Vivienda'), ('servicios', 'Servicios'), ('educacion', 'Educación'), ('salud', 'Salud'), ('entretenimiento', 'Entretenimiento'), ('ropa', 'Ropa'), ('deudas', 'Pago de Deudas'), ('ahorro', 'Ahorro'), ('otro_gasto', 'Otro Gasto')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro Financiero',
                'verbose_name_plural': 'Registros Financieros',
                'db_table': 'registro_financiero',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ReporteFinanciero',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('total_ingresos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_gastos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detalle_por_categoria', models.JSONField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte Financiero',
                'verbose_name_plural': 'Reportes Financieros',
                'db_table': 'reporte_financiero',
                'ordering': ['-anio', '-mes'],
            },
        ),
    ]
