# Generated by Django 5.2.7 on 2025-10-01 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        ('oportunidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metafinanciera',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_financieras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrofinanciero',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_financieros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrofinanciero',
            name='oportunidad',
            field=models.ForeignKey(blank=True, help_text='Oportunidad económica relacionada con este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_financieros', to='oportunidades.oportunidadeconomica'),
        ),
        migrations.AddField(
            model_name='reportefinanciero',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_financieros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reportefinanciero',
            unique_together={('id_usuario', 'mes', 'anio')},
        ),
    ]
