# Generated by Django 5.2.8 on 2025-11-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrofinanciero',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
