# Generated by Django 5.2.8 on 2025-11-22 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_alter_registrofinanciero_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrofinanciero',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
