# Generated by Django 5.2.8 on 2025-11-26 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_alter_registrofinanciero_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportefinanciero',
            options={'ordering': ['-anio', '-semana'], 'verbose_name': 'Reporte Financiero', 'verbose_name_plural': 'Reportes Financieros'},
        ),
        migrations.RenameField(
            model_name='reportefinanciero',
            old_name='mes',
            new_name='semana',
        ),
        migrations.AlterUniqueTogether(
            name='reportefinanciero',
            unique_together={('id_usuario', 'semana', 'anio')},
        ),
        migrations.AddField(
            model_name='reportefinanciero',
            name='fecha_fin_semana',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportefinanciero',
            name='fecha_inicio_semana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
