# Generated by Django 5.2.7 on 2025-10-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OportunidadEconomica',
            fields=[
                ('id_oportunidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('beca', 'Beca'), ('subvencion', 'Subvención'), ('credito', 'Crédito Educativo'), ('empleo', 'Oportunidad de Empleo'), ('capacitacion', 'Capacitación Gratuita'), ('emprendimiento', 'Apoyo a Emprendimiento')], max_length=20)),
                ('institucion', models.CharField(max_length=200)),
                ('enlace', models.URLField()),
                ('descripcion', models.TextField()),
                ('requisitos', models.TextField()),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Oportunidad Económica',
                'verbose_name_plural': 'Oportunidades Económicas',
                'db_table': 'oportunidad_economica',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
